### ISSUE TITLE
[BUG] Poblem with srarting in k8s with volumes on nfs

### ISSUE THREAD

**Issue by vonProteus** [linuxserver/docker-bazarr#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when starting from scratch in k8s 
i get 
```
kubectl logs bazarr-674d499b9f-r9zwf --container=bazarr --namespace=multimedia --follow=true
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

chown: changing ownership of '/config': Operation not permitted
chown: changing ownership of '/config': Operation not permitted
s6-rc: warning: unable to start service init-bazarr-config: command exited 1

```
i think it is related to mounting volumes with config from nfs
permissions are set correctly on nfs folder and all its conntent is own by 1000:1000

### Expected Behavior

i would like to be able to run bazarr with volumes on nfs

### Steps To Reproduce

kubectl apply this 
```
apiVersion: v1
kind: Namespace
metadata:
  name: multimedia
---
apiVersion: v1
data:
  process_group_id: "1000"
  process_user_id: "1000"
  time_zone: UTC
kind: ConfigMap
metadata:
  name: configuration-8mf2964hh6
  namespace: multimedia
---
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: multimedia-secrets-46f8b28mk5
  namespace: multimedia
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bazarr
  name: bazarr
  namespace: multimedia
spec:
  ports:
  - name: web
    port: 80
    targetPort: 6767
  - name: bazarr-web
    port: 6767
  selector:
    app: bazarr
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-hdd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1.0Ti
  storageClassName: nfs-hdd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvs
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1.0Ti
  storageClassName: nfs-hdd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bazarr
  name: bazarr
  namespace: multimedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: time_zone
              name: configuration-8mf2964hh6
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: process_user_id
              name: configuration-8mf2964hh6
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: process_group_id
              name: configuration-8mf2964hh6
        image: linuxserver/bazarr
        imagePullPolicy: Always
        name: bazarr
        ports:
        - containerPort: 6767
          name: web
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /tv
          name: tvs
        - mountPath: /movies
          name: movies
        - mountPath: /tmp
          name: tmp
        - mountPath: /dev/shm
          name: shm
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp
      - emptyDir:
          medium: Memory
        name: shm
      - name: config
        persistentVolumeClaim:
          claimName: bazarr
      - name: tvs
        persistentVolumeClaim:
          claimName: tvs
      - name: movies
        persistentVolumeClaim:
          claimName: movies
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-route
  namespace: multimedia
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`bazarr(public_domain)`)
    services:
    - kind: Service
      name: bazarr
      port: 80
  tls:
    certResolver: letsencrypt
```
and look into container logs

### Environment

```markdown
- OS: debian 
- How docker service was installed:  curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.23.14+k3s1" INSTALL_K3S_EXEC="--no-deploy=traefik --service-node-port-range=1-65535" sh -
```

### CPU architecture

x86-64

### Docker creation

```bash
kubectl apply -k .
```

### Container logs

```bash
kubectl  logs bazarr-5b495477fc-z69sp --container=bazarr --namespace=multimedia --follow=true
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

chown: changing ownership of '/config': Operation not permitted
chown: changing ownership of '/config': Operation not permitted
s6-rc: warning: unable to start service init-bazarr-config: command exited 1
```
