### ISSUE TITLE
[FEAT] Add the mediainfo optional dependency

### ISSUE THREAD

**Issue by pums974** [linuxserver/docker-bazarr#105]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Can you install `mediainfo` in the docker ?

### Reason for change

In recent version of `bazaar`, `mediainfo` can be used to parse embedded subtitles video.
It must be installed in the docker for it to work.

### Proposed code change

add mediainfo during the install phase:
```bash
echo "**** install packages ****" && \
  apk add --no-cache \
    ffmpeg \
    libxml2 \
    libxslt \
    mediainfo \ # optional dependency for embedded subtitles video
    python3 && \
```

**Comment by Freekers** [comment]
You can do so yourself using the following Docker Mod: https://github.com/linuxserver/docker-mods/tree/universal-package-install

It's really easy. Here's a excerpt from my docker-compose for HASS, but you get the point:

```
services:
  hass:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: hass
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - PUID=1000
     - PGID=1000
     - DOCKER_MODS=linuxserver/mods:universal-package-install
     - INSTALL_PACKAGES=android-tools
  ```
