### ISSUE TITLE
[FEAT] documentation on docker compose healthcheck

### ISSUE THREAD

**Issue by TrueOsiris** [linuxserver/docker-bazarr#138]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would you be so kind to add a section on a docker compose healthcheck in the readme.me

### Reason for change

it took me a while crawling the internet, grabbing bits and pieces all around on obscure fora to get the information.
And a docker healthcheck is quite a common thing in modern solutions.

## Docker Compose healthcheck

After running the bazarr container without a healthcheck, access the gui and read out the api key.

Add a docker secrets file, as mentioned above, or add a line to the .env file.
```
BAZARRAPIKEY=yourapikey
```
Then add the healthcheck section to to the docker compose file and restart the container.<br>
The env_file lines are optional, as a docker compose container should always look for a .env.

```yaml
---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file:
      - ./.env  
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/bazarr/config:/config
      - /path/to/movies:/movies #optional
      - /path/to/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://127.0.0.1:6767/api/system/status?apikey=$$BAZARRAPIKEY || exit 1"]
      interval: 30s # n° seconds to initially wait before executing the health check + frequency of subsequent health checks.
      timeout: 10s # n° of seconds Docker awaits for your health check command to return an exit code before declaring it as failed.
      retries: 5  # n° of consecutive health check failures required to declare the container as unhealthy.
      start_period: 30s  # wait before starting the healthcheck after container launch
```
