### ISSUE TITLE
start page logo not working with domain subpath

### ISSUE THREAD

**Issue by cybermcm** [linuxserver/docker-bazarr#92]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
logo on start page should appear (logo128.png)

## Current Behavior
logo is loaded without domain subpath, currently I'm using bazarr with https://domain.com/bazarr/
should be: https://domain.com/bazarr/static/logo128.png
currently: https://domain.com/static/logo128.png -> Result 404

## Steps to Reproduce
every other image is loading after login, only main logo on logon screen doesn't include bazarr subpath

## Environment
**OS: Linux s01 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux**
**CPU architecture:** x86_64
**How docker service was installed:**
official docker repo
bazarr config.ini contains `base_url = /bazarr`

## Command used to create docker container (run/create/compose/screenshot)
```
bazarr:
  image: lscr.io/linuxserver/bazarr
  container_name: bazarr
  environment:
   - PUID=911
   - PGID=911
   - TZ=${TZ}
  labels:
   - ${WATCHTOWER_TRUE}
   - traefik.enable=true
   - "traefik.http.routers.bazarr.rule=Host(`${HOSTNAME}`) && PathPrefix(`/bazarr`)"
   - traefik.http.routers.bazarr.entrypoints=web-secure
   - traefik.http.routers.bazarr.tls.certresolver=le
   - traefik.http.routers.bazarr.tls=true
   - traefik.http.routers.bazarr.priority=2
   - traefik.http.routers.bazarr.tls.options=default
   - traefik.http.routers.bazarr.middlewares=bazarr
   - traefik.http.middlewares.bazarr.headers.customresponseheaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
   - traefik.http.services.bazarr.loadbalancer.server.port=6767
  networks:
   - web
  restart: always
  volumes:
   - ${DOCKER_PATH}/bazarr:/config
   - /_downloads:/downloads
   - /_downloads/tv:/tv
```

## Docker logs
```
bazarr                  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
bazarr                  | [s6-init] ensuring user provided files have correct perms...exited 0.
bazarr                  | [fix-attrs.d] applying ownership & permissions fixes...
bazarr                  | [fix-attrs.d] done.
bazarr                  | [cont-init.d] executing container initialization scripts...
bazarr                  | [cont-init.d] 01-envfile: executing...
bazarr                  | [cont-init.d] 01-envfile: exited 0.
bazarr                  | [cont-init.d] 02-tamper-check: executing...
bazarr                  | [cont-init.d] 02-tamper-check: exited 0.
bazarr                  | [cont-init.d] 10-adduser: executing...
bazarr                  | usermod: no changes
bazarr                  |
bazarr                  | -------------------------------------
bazarr                  |           _         ()
bazarr                  |          | |  ___   _    __
bazarr                  |          | | / __| | |  /  \
bazarr                  |          | | \__ \ | | | () |
bazarr                  |          |_| |___/ |_|  \__/
bazarr                  |
bazarr                  |
bazarr                  | Brought to you by linuxserver.io
bazarr                  | -------------------------------------
bazarr                  |
bazarr                  | To support the app dev(s) visit:
bazarr                  | Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url
bazarr                  |
bazarr                  | To support LSIO projects visit:
bazarr                  | https://www.linuxserver.io/donate/
bazarr                  | -------------------------------------
bazarr                  | GID/UID
bazarr                  | -------------------------------------
bazarr                  |
bazarr                  | User uid:    911
bazarr                  | User gid:    911
bazarr                  | -------------------------------------
bazarr                  |
bazarr                  | [cont-init.d] 10-adduser: exited 0.
bazarr                  | [cont-init.d] 30-config: executing...
bazarr                  | [cont-init.d] 30-config: exited 0.
bazarr                  | [cont-init.d] 90-custom-folders: executing...
bazarr                  | [cont-init.d] 90-custom-folders: exited 0.
bazarr                  | [cont-init.d] 99-custom-files: executing...
bazarr                  | [custom-init] no custom files found exiting...
bazarr                  | [cont-init.d] 99-custom-files: exited 0.
bazarr                  | [cont-init.d] done.
bazarr                  | [services.d] starting services
bazarr                  | [services.d] done.
bazarr                  | /app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sonarr.domain.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
bazarr                  |   warnings.warn(
bazarr                  | 2022-05-07 14:39:50,136 - root                             (7f00de71eb38) :  INFO (signalr_client:40) - BAZARR trying to connect to Sonarr SignalR feed...
bazarr                  | 2022-05-07 14:39:50,136 - root                             (7f00ecafcb48) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767/bazarr
bazarr                  | 2022-05-07 14:39:50,258 - root                             (7f00de71eb38) :  INFO (signalr_client:55) - BAZARR SignalR client for Sonarr is connected and waiting for events.

```
