### ISSUE TITLE
Bazarr crashing when I load /series on a container with base image Alpine 3.15

### ISSUE THREAD

**Issue by germancasares** [linuxserver/docker-bazarr#93]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Crossposting from: https://github.com/morpheus65535/bazarr/issues/1860 

But the current version of the base image used for docker-bazarr (Alpine 3.15) contains an older library of sqlite-libs that it is making it crash on my Raspberry Pi 3b. I tested this and it was working fine on a Raspberry Pi 4b.

------------------------------

## Expected Behavior
Bazarr UI working correctly.

## Current Behavior
Bazarr UI crashes with Segmentation Fault.

## Steps to Reproduce

1. Setup Bazarr with Sonarr
2. Go to BAZARR_URL:6767/series
3. The page will eventually crash with "Cannot Initialize Bazarr"

## Environment
**OS:** Raspbery Pi OS
**CPU architecture:** arm64
**Hardware:** Raspberry Pi 3b (It does not happen on Raspberry Pi 4b) 
**How docker service was installed:** lscr.io/linuxserver/bazarr:latest

## Command used to create docker container (run/create/compose/screenshot)

```
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    depends_on:
      - sonarr
      - radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /home/USER/Bazarr:/config
      - /media/USER/Movies:/movies
      - /media/USER/TV Shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
```
